name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Print Node.js and npm versions
        run: node -v && npm -v

      - name: Install dependencies
        run: npm install

      - name: Check code formatting
        run: npm run prettier:check

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
